/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited.
// It is regenerated by Next.js and committed so `tsc --noEmit` resolves Next
// ambient types in CI without a prior `next build`.
// See https://nextjs.org/docs/app/api-reference/config/typescript for more information.
