// Per-block attribute validation (origin §4.2, Q8). Three concerns, layered on
// the block.json key/type surface:
//   1. unknown-key rejection — a key that is neither block-specific (block.json)
//      nor a common `supports`-derived attribute is rejected, because WordPress
//      silently drops unknown attributes (the §2.4 silent-drop hazard).
//   2. value-range overlay — the correctness-critical ranges block.json does NOT
//      carry (heading.level in 1..6, cover.dimRatio in 0..100, columns.align).
//   3. URL safe-scheme — URL-valued attributes reject `javascript:`/`data:` and
//      other dangerous schemes (the stored-XSS vector, §6.4), which block.json
//      types as a plain `string` with no scheme constraint.
//
// Pure functions over the extracted surface; no IR dependency. U4 layer-2a calls
// validateAttributes per node and maps the violations onto the error format.
import { type AllowedBlockName } from "./allowlist";
import { getCoreAttributeKeys } from "./block-json";

export type AttributeViolationKind =
  | "UNKNOWN_ATTRIBUTE"
  | "ATTRIBUTE_OUT_OF_RANGE"
  | "UNSAFE_URL";

export interface AttributeViolation {
  kind: AttributeViolationKind;
  block: AllowedBlockName;
  attribute: string;
  message: string;
}

// Attribute keys generated by core block `supports` (alignment, color,
// typography, spacing, layout, anchor, custom class). These are legitimate on
// (almost) any block but are NOT listed in block.json `attributes`, so they are
// allowed globally — without this the unknown-key guard would reject every
// styled block in the seed patterns.
const COMMON_SUPPORTS_ATTRS = new Set<string>([
  "align",
  "textAlign",
  "anchor",
  "ariaLabel",
  "className",
  "lock",
  "metadata",
  "style",
  "backgroundColor",
  "textColor",
  "gradient",
  "fontSize",
  "fontFamily",
  "borderColor",
  "layout",
]);

type RangeCheck = (value: unknown) => boolean;

// The thin hand-authored value-range overlay — only the ranges that matter for
// the catch invariant and are absent from block.json (origin §4.2).
const VALUE_RANGES: Partial<Record<AllowedBlockName, Record<string, RangeCheck>>> = {
  "core/heading": {
    level: (v) => Number.isInteger(v) && (v as number) >= 1 && (v as number) <= 6,
  },
  "core/cover": {
    dimRatio: (v) => typeof v === "number" && Number.isFinite(v) && v >= 0 && v <= 100,
  },
  "core/columns": {
    align: (v) => v === "wide" || v === "full",
  },
};

// URL-valued attributes that get the safe-scheme check (origin §4.2). block.json
// types these as plain strings, so the scheme constraint is ours to enforce.
const URL_ATTRIBUTES: Partial<Record<AllowedBlockName, readonly string[]>> = {
  "core/button": ["url"],
  "core/social-link": ["url"],
  "core/image": ["url", "href"],
};

const SAFE_URL_SCHEMES = new Set(["http", "https", "mailto", "tel"]);

// Strip all whitespace (incl. Unicode), control characters (C0/C1), and format
// characters (zero-width spaces, BOM) before scheme detection. Browsers strip
// ASCII whitespace/controls when resolving an href; stripping a conservative
// SUPERSET here means the validator can never treat a string as scheme-less
// (and thus "safe") that a current-or-future consumer would resolve to a
// dangerous scheme. Catches tab/space/newline, no-break space, zero-width
// space, and BOM inserted into or before the scheme.
const STRIP_NON_URL = /[\s\p{Cc}\p{Cf}]/gu;
const SCHEME = /^([a-z][a-z0-9+.-]*):/i;

/**
 * Safe-scheme check for URL-valued attributes. Relative URLs and fragments (no
 * scheme) are allowed; an explicit scheme must be one of http/https/mailto/tel.
 * Whitespace and control characters are stripped first so `java\tscript:` /
 * ` javascript:` / `\x00javascript:` evasions are caught.
 */
export function isSafeUrl(value: string): boolean {
  const normalized = value.replace(STRIP_NON_URL, "");
  const match = SCHEME.exec(normalized);
  if (!match) return true; // relative URL, fragment, or query — no scheme to abuse
  return SAFE_URL_SCHEMES.has(match[1]!.toLowerCase());
}

/**
 * Validate a block's attributes against the extracted key surface + overlay.
 * Returns every violation; an empty array means the attributes are legal.
 */
export function validateAttributes(
  block: AllowedBlockName,
  attributes: Record<string, unknown>,
): AttributeViolation[] {
  const violations: AttributeViolation[] = [];
  const knownKeys = getCoreAttributeKeys(block);
  const ranges = VALUE_RANGES[block];
  const urlAttrs = URL_ATTRIBUTES[block];

  for (const [key, value] of Object.entries(attributes)) {
    if (!knownKeys.has(key) && !COMMON_SUPPORTS_ATTRS.has(key)) {
      violations.push({
        kind: "UNKNOWN_ATTRIBUTE",
        block,
        attribute: key,
        message: `Unknown attribute '${key}' on ${block}.`,
      });
      continue; // an unknown key has no meaningful range/URL semantics
    }

    const check = ranges?.[key];
    if (check && !check(value)) {
      violations.push({
        kind: "ATTRIBUTE_OUT_OF_RANGE",
        block,
        attribute: key,
        message: `Attribute '${key}' on ${block} has an out-of-range value: ${JSON.stringify(value)}.`,
      });
      continue;
    }

    if (urlAttrs?.includes(key) && typeof value === "string" && !isSafeUrl(value)) {
      violations.push({
        kind: "UNSAFE_URL",
        block,
        attribute: key,
        message: `Attribute '${key}' on ${block} uses a disallowed URL scheme: ${JSON.stringify(value)}.`,
      });
    }
  }

  return violations;
}
